import type { Metadata } from 'next';
import { Inter, Dosis, Inconsolata } from 'next/font/google';
import './globals.css';

export const dosis = Dosis({ subsets: ['latin'], variable: '--font-dosis' });
export const inconsolata = Inconsolata({
  subsets: ['latin'],
  variable: '--font-inconsolata',
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`w-full ${dosis.variable} ${inconsolata.variable}`}
    >
      <body className={inter.className}>{children}</body>
    </html>
  );
}
